# back/Dockerfile.dev（airホットリロード開発用）
FROM golang:1.25

WORKDIR /app

ENV GO111MODULE=on

# airのインストール
RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
